// Temporary mock data for dashboard UI development.
// Replace each export with real API/database data when the backend is ready.
// Today's date for reference: 2026-07-02

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type UserRole = "ADMIN" | "MANAGER" | "EMPLOYEE";
export type UserStatus = "ACTIVE" | "INACTIVE" | "SUSPENDED";
export type EmployeeStatus = "ACTIVE" | "INACTIVE" | "SUSPENDED";
export type AttendanceStatus =
  | "PRESENT"
  | "LATE"
  | "HALF_DAY"
  | "ABSENT"
  | "ON_LEAVE"
  | "MISSING_CHECKOUT";
export type AbsenceStatus = "ABSENT" | "ON_LEAVE" | "UNEXCUSED";
export type AttendanceEventType =
  | "CHECK_IN"
  | "CHECK_OUT"
  | "LATE_CHECK_IN"
  | "MISSING_CHECKOUT"
  | "ADMIN_CORRECTION"
  | "REJECTED_LOCATION";
export type AttendanceSource = "WEB" | "ADMIN_CORRECTION" | "SYSTEM";

// ---------------------------------------------------------------------------
// 1. Current User
// ---------------------------------------------------------------------------

export const currentUser = {
  id: "user-001",
  name: "Sarah Al-Otaibi",
  email: "sarah.otaibi@company.com",
  role: "ADMIN" as UserRole,
  status: "ACTIVE" as UserStatus,
  employeeId: "emp-001",
  avatarUrl: null as string | null,
};

// ---------------------------------------------------------------------------
// 2. Employees
// ---------------------------------------------------------------------------

export const employees = [
  {
    id: "emp-001",
    userId: "user-001",
    employeeCode: "EMP-0001",
    name: "Sarah Al-Otaibi",
    email: "sarah.otaibi@company.com",
    phone: "+966-50-111-0001",
    department: "HR",
    jobTitle: "HR Manager",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2022-03-01",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-002",
    userId: "user-002",
    employeeCode: "EMP-0002",
    name: "Khalid Bin Nasser",
    email: "khalid.nasser@company.com",
    phone: "+966-50-111-0002",
    department: "Engineering",
    jobTitle: "Senior Software Engineer",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2021-06-15",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-003",
    userId: "user-003",
    employeeCode: "EMP-0003",
    name: "Fatima Al-Zahrani",
    email: "fatima.zahrani@company.com",
    phone: "+966-50-111-0003",
    department: "Finance",
    jobTitle: "Financial Analyst",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2023-01-10",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-004",
    userId: "user-004",
    employeeCode: "EMP-0004",
    name: "Omar Al-Harbi",
    email: "omar.harbi@company.com",
    phone: "+966-50-111-0004",
    department: "Operations",
    jobTitle: "Operations Coordinator",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2020-09-20",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-005",
    userId: "user-005",
    employeeCode: "EMP-0005",
    name: "Noura Al-Qahtani",
    email: "noura.qahtani@company.com",
    phone: "+966-50-111-0005",
    department: "Sales",
    jobTitle: "Sales Executive",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2022-11-05",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-006",
    userId: "user-006",
    employeeCode: "EMP-0006",
    name: "Ahmed Al-Dossari",
    email: "ahmed.dossari@company.com",
    phone: "+966-50-111-0006",
    department: "Engineering",
    jobTitle: "Frontend Developer",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2023-04-01",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-007",
    userId: "user-007",
    employeeCode: "EMP-0007",
    name: "Reem Al-Mutairi",
    email: "reem.mutairi@company.com",
    phone: "+966-50-111-0007",
    department: "Support",
    jobTitle: "Customer Support Specialist",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2024-02-14",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-008",
    userId: "user-008",
    employeeCode: "EMP-0008",
    name: "Tariq Al-Ghamdi",
    email: "tariq.ghamdi@company.com",
    phone: "+966-50-111-0008",
    department: "Engineering",
    jobTitle: "Backend Developer",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2022-07-18",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-009",
    userId: "user-009",
    employeeCode: "EMP-0009",
    name: "Hessa Al-Shehri",
    email: "hessa.shehri@company.com",
    phone: "+966-50-111-0009",
    department: "Finance",
    jobTitle: "Accountant",
    status: "INACTIVE" as EmployeeStatus,
    hiredAt: "2019-05-12",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-010",
    userId: "user-010",
    employeeCode: "EMP-0010",
    name: "Mansour Al-Aqili",
    email: "mansour.aqili@company.com",
    phone: "+966-50-111-0010",
    department: "Sales",
    jobTitle: "Sales Manager",
    status: "SUSPENDED" as EmployeeStatus,
    hiredAt: "2018-12-01",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-011",
    userId: "user-011",
    employeeCode: "EMP-0011",
    name: "Lina Al-Sulami",
    email: "lina.sulami@company.com",
    phone: "+966-50-111-0011",
    department: "HR",
    jobTitle: "HR Coordinator",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2023-08-22",
    avatarUrl: null as string | null,
  },
  {
    id: "emp-012",
    userId: "user-012",
    employeeCode: "EMP-0012",
    name: "Faris Al-Rashidi",
    email: "faris.rashidi@company.com",
    phone: "+966-50-111-0012",
    department: "Operations",
    jobTitle: "Logistics Officer",
    status: "ACTIVE" as EmployeeStatus,
    hiredAt: "2021-03-30",
    avatarUrl: null as string | null,
  },
];

// ---------------------------------------------------------------------------
// 3. Attendance Records (current month: July 2026)
// ---------------------------------------------------------------------------

export const attendanceRecords = [
  // 2026-07-01 (Wednesday)
  {
    id: "att-001",
    employeeId: "emp-002",
    employeeName: "Khalid Bin Nasser",
    department: "Engineering",
    date: "2026-07-01",
    checkInAt: "2026-07-01T08:02:00Z",
    checkOutAt: "2026-07-01T17:05:00Z",
    totalMinutes: 543,
    status: "PRESENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 45,
    checkOutDistanceMeters: 52,
  },
  {
    id: "att-002",
    employeeId: "emp-003",
    employeeName: "Fatima Al-Zahrani",
    department: "Finance",
    date: "2026-07-01",
    checkInAt: "2026-07-01T08:47:00Z",
    checkOutAt: "2026-07-01T17:00:00Z",
    totalMinutes: 493,
    status: "LATE" as AttendanceStatus,
    isLate: true,
    lateMinutes: 47,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 88,
    checkOutDistanceMeters: 91,
  },
  {
    id: "att-003",
    employeeId: "emp-004",
    employeeName: "Omar Al-Harbi",
    department: "Operations",
    date: "2026-07-01",
    checkInAt: "2026-07-01T08:00:00Z",
    checkOutAt: null,
    totalMinutes: null,
    status: "MISSING_CHECKOUT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 34,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-004",
    employeeId: "emp-005",
    employeeName: "Noura Al-Qahtani",
    department: "Sales",
    date: "2026-07-01",
    checkInAt: null,
    checkOutAt: null,
    totalMinutes: 0,
    status: "ABSENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "SYSTEM" as AttendanceSource,
    checkInDistanceMeters: null,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-005",
    employeeId: "emp-006",
    employeeName: "Ahmed Al-Dossari",
    department: "Engineering",
    date: "2026-07-01",
    checkInAt: "2026-07-01T08:05:00Z",
    checkOutAt: "2026-07-01T12:30:00Z",
    totalMinutes: 265,
    status: "HALF_DAY" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 67,
    checkOutDistanceMeters: 71,
  },
  {
    id: "att-006",
    employeeId: "emp-007",
    employeeName: "Reem Al-Mutairi",
    department: "Support",
    date: "2026-07-01",
    checkInAt: null,
    checkOutAt: null,
    totalMinutes: null,
    status: "ON_LEAVE" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "SYSTEM" as AttendanceSource,
    checkInDistanceMeters: null,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-007",
    employeeId: "emp-008",
    employeeName: "Tariq Al-Ghamdi",
    department: "Engineering",
    date: "2026-07-01",
    checkInAt: "2026-07-01T07:58:00Z",
    checkOutAt: "2026-07-01T17:02:00Z",
    totalMinutes: 544,
    status: "PRESENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 29,
    checkOutDistanceMeters: 41,
  },
  // 2026-07-02 (Thursday — today)
  {
    id: "att-008",
    employeeId: "emp-002",
    employeeName: "Khalid Bin Nasser",
    department: "Engineering",
    date: "2026-07-02",
    checkInAt: "2026-07-02T08:01:00Z",
    checkOutAt: null,
    totalMinutes: null,
    status: "PRESENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 38,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-009",
    employeeId: "emp-003",
    employeeName: "Fatima Al-Zahrani",
    department: "Finance",
    date: "2026-07-02",
    checkInAt: "2026-07-02T09:15:00Z",
    checkOutAt: null,
    totalMinutes: null,
    status: "LATE" as AttendanceStatus,
    isLate: true,
    lateMinutes: 75,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 112,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-010",
    employeeId: "emp-004",
    employeeName: "Omar Al-Harbi",
    department: "Operations",
    date: "2026-07-02",
    checkInAt: "2026-07-02T08:00:00Z",
    checkOutAt: null,
    totalMinutes: null,
    status: "PRESENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 55,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-011",
    employeeId: "emp-005",
    employeeName: "Noura Al-Qahtani",
    department: "Sales",
    date: "2026-07-02",
    checkInAt: null,
    checkOutAt: null,
    totalMinutes: 0,
    status: "ABSENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "SYSTEM" as AttendanceSource,
    checkInDistanceMeters: null,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-012",
    employeeId: "emp-006",
    employeeName: "Ahmed Al-Dossari",
    department: "Engineering",
    date: "2026-07-02",
    checkInAt: "2026-07-02T08:10:00Z",
    checkOutAt: null,
    totalMinutes: null,
    status: "PRESENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 78,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-013",
    employeeId: "emp-007",
    employeeName: "Reem Al-Mutairi",
    department: "Support",
    date: "2026-07-02",
    checkInAt: null,
    checkOutAt: null,
    totalMinutes: null,
    status: "ON_LEAVE" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "SYSTEM" as AttendanceSource,
    checkInDistanceMeters: null,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-014",
    employeeId: "emp-008",
    employeeName: "Tariq Al-Ghamdi",
    department: "Engineering",
    date: "2026-07-02",
    checkInAt: "2026-07-02T08:30:00Z",
    checkOutAt: null,
    totalMinutes: null,
    status: "LATE" as AttendanceStatus,
    isLate: true,
    lateMinutes: 30,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 62,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-015",
    employeeId: "emp-011",
    employeeName: "Lina Al-Sulami",
    department: "HR",
    date: "2026-07-02",
    checkInAt: "2026-07-02T07:55:00Z",
    checkOutAt: null,
    totalMinutes: null,
    status: "PRESENT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "WEB" as AttendanceSource,
    checkInDistanceMeters: 22,
    checkOutDistanceMeters: null,
  },
  {
    id: "att-016",
    employeeId: "emp-012",
    employeeName: "Faris Al-Rashidi",
    department: "Operations",
    date: "2026-07-02",
    checkInAt: null,
    checkOutAt: null,
    totalMinutes: null,
    status: "MISSING_CHECKOUT" as AttendanceStatus,
    isLate: false,
    lateMinutes: 0,
    source: "SYSTEM" as AttendanceSource,
    checkInDistanceMeters: null,
    checkOutDistanceMeters: null,
  },
];

// ---------------------------------------------------------------------------
// 4. Absences
// ---------------------------------------------------------------------------

export const absences = [
  {
    id: "abs-001",
    employeeId: "emp-005",
    employeeName: "Noura Al-Qahtani",
    department: "Sales",
    date: "2026-07-01",
    status: "UNEXCUSED" as AbsenceStatus,
    reason: "No check-in recorded. Employee did not notify HR.",
  },
  {
    id: "abs-002",
    employeeId: "emp-005",
    employeeName: "Noura Al-Qahtani",
    department: "Sales",
    date: "2026-07-02",
    status: "ABSENT" as AbsenceStatus,
    reason: "Personal emergency. Employee informed manager via phone.",
  },
  {
    id: "abs-003",
    employeeId: "emp-007",
    employeeName: "Reem Al-Mutairi",
    department: "Support",
    date: "2026-07-01",
    status: "ON_LEAVE" as AbsenceStatus,
    reason: "Annual leave approved",
  },
  {
    id: "abs-004",
    employeeId: "emp-007",
    employeeName: "Reem Al-Mutairi",
    department: "Support",
    date: "2026-07-02",
    status: "ON_LEAVE" as AbsenceStatus,
    reason: "Annual leave approved",
  },
];

// ---------------------------------------------------------------------------
// 5. Monthly Employee Attendance Summaries (July 2026, partial — 2 days in)
// ---------------------------------------------------------------------------

export const employeeMonthlySummaries = [
  {
    employeeId: "emp-002",
    employeeName: "Khalid Bin Nasser",
    department: "Engineering",
    month: "2026-07",
    presentDays: 2,
    lateDays: 0,
    absentDays: 0,
    halfDays: 0,
    leaveDays: 0,
    missingCheckoutDays: 0,
    totalWorkedMinutes: 543,
    averageWorkedMinutes: 272,
  },
  {
    employeeId: "emp-003",
    employeeName: "Fatima Al-Zahrani",
    department: "Finance",
    month: "2026-07",
    presentDays: 0,
    lateDays: 2,
    absentDays: 0,
    halfDays: 0,
    leaveDays: 0,
    missingCheckoutDays: 0,
    totalWorkedMinutes: 493,
    averageWorkedMinutes: 247,
  },
  {
    employeeId: "emp-004",
    employeeName: "Omar Al-Harbi",
    department: "Operations",
    month: "2026-07",
    presentDays: 1,
    lateDays: 0,
    absentDays: 0,
    halfDays: 0,
    leaveDays: 0,
    missingCheckoutDays: 1,
    totalWorkedMinutes: 0,
    averageWorkedMinutes: 0,
  },
  {
    employeeId: "emp-005",
    employeeName: "Noura Al-Qahtani",
    department: "Sales",
    month: "2026-07",
    presentDays: 0,
    lateDays: 0,
    absentDays: 2,
    halfDays: 0,
    leaveDays: 0,
    missingCheckoutDays: 0,
    totalWorkedMinutes: 0,
    averageWorkedMinutes: 0,
  },
  {
    employeeId: "emp-006",
    employeeName: "Ahmed Al-Dossari",
    department: "Engineering",
    month: "2026-07",
    presentDays: 1,
    lateDays: 0,
    absentDays: 0,
    halfDays: 1,
    leaveDays: 0,
    missingCheckoutDays: 0,
    totalWorkedMinutes: 265,
    averageWorkedMinutes: 133,
  },
  {
    employeeId: "emp-007",
    employeeName: "Reem Al-Mutairi",
    department: "Support",
    month: "2026-07",
    presentDays: 0,
    lateDays: 0,
    absentDays: 0,
    halfDays: 0,
    leaveDays: 2,
    missingCheckoutDays: 0,
    totalWorkedMinutes: 0,
    averageWorkedMinutes: 0,
  },
  {
    employeeId: "emp-008",
    employeeName: "Tariq Al-Ghamdi",
    department: "Engineering",
    month: "2026-07",
    presentDays: 1,
    lateDays: 1,
    absentDays: 0,
    halfDays: 0,
    leaveDays: 0,
    missingCheckoutDays: 0,
    totalWorkedMinutes: 544,
    averageWorkedMinutes: 272,
  },
  {
    employeeId: "emp-011",
    employeeName: "Lina Al-Sulami",
    department: "HR",
    month: "2026-07",
    presentDays: 1,
    lateDays: 0,
    absentDays: 0,
    halfDays: 0,
    leaveDays: 0,
    missingCheckoutDays: 0,
    totalWorkedMinutes: 0,
    averageWorkedMinutes: 0,
  },
  {
    employeeId: "emp-012",
    employeeName: "Faris Al-Rashidi",
    department: "Operations",
    month: "2026-07",
    presentDays: 0,
    lateDays: 0,
    absentDays: 0,
    halfDays: 0,
    leaveDays: 0,
    missingCheckoutDays: 1,
    totalWorkedMinutes: 0,
    averageWorkedMinutes: 0,
  },
];

// ---------------------------------------------------------------------------
// 6. Dashboard Summary (as of today: 2026-07-02)
// ---------------------------------------------------------------------------

export const dashboardSummary = {
  totalActiveEmployees: 10,
  presentToday: 5,
  lateToday: 2,
  absentToday: 1,
  missingCheckoutToday: 1,
  averageWorkingHours: 8.4,
};

// ---------------------------------------------------------------------------
// 7. Recent Attendance Events
// ---------------------------------------------------------------------------

export const recentAttendanceEvents = [
  {
    id: "evt-001",
    employeeId: "emp-011",
    employeeName: "Lina Al-Sulami",
    department: "HR",
    type: "CHECK_IN" as AttendanceEventType,
    timestamp: "2026-07-02T07:55:00Z",
    status: "PRESENT" as AttendanceStatus,
    message: "Checked in on time.",
  },
  {
    id: "evt-002",
    employeeId: "emp-002",
    employeeName: "Khalid Bin Nasser",
    department: "Engineering",
    type: "CHECK_IN" as AttendanceEventType,
    timestamp: "2026-07-02T08:01:00Z",
    status: "PRESENT" as AttendanceStatus,
    message: "Checked in on time.",
  },
  {
    id: "evt-003",
    employeeId: "emp-004",
    employeeName: "Omar Al-Harbi",
    department: "Operations",
    type: "CHECK_IN" as AttendanceEventType,
    timestamp: "2026-07-02T08:00:00Z",
    status: "PRESENT" as AttendanceStatus,
    message: "Checked in on time.",
  },
  {
    id: "evt-004",
    employeeId: "emp-006",
    employeeName: "Ahmed Al-Dossari",
    department: "Engineering",
    type: "CHECK_IN" as AttendanceEventType,
    timestamp: "2026-07-02T08:10:00Z",
    status: "PRESENT" as AttendanceStatus,
    message: "Checked in on time.",
  },
  {
    id: "evt-005",
    employeeId: "emp-008",
    employeeName: "Tariq Al-Ghamdi",
    department: "Engineering",
    type: "LATE_CHECK_IN" as AttendanceEventType,
    timestamp: "2026-07-02T08:30:00Z",
    status: "LATE" as AttendanceStatus,
    message: "Checked in 30 minutes late.",
  },
  {
    id: "evt-006",
    employeeId: "emp-003",
    employeeName: "Fatima Al-Zahrani",
    department: "Finance",
    type: "LATE_CHECK_IN" as AttendanceEventType,
    timestamp: "2026-07-02T09:15:00Z",
    status: "LATE" as AttendanceStatus,
    message: "Checked in 75 minutes late.",
  },
  {
    id: "evt-007",
    employeeId: "emp-004",
    employeeName: "Omar Al-Harbi",
    department: "Operations",
    type: "MISSING_CHECKOUT" as AttendanceEventType,
    timestamp: "2026-07-01T17:30:00Z",
    status: "MISSING_CHECKOUT" as AttendanceStatus,
    message: "No check-out recorded for 2026-07-01.",
  },
  {
    id: "evt-008",
    employeeId: "emp-002",
    employeeName: "Khalid Bin Nasser",
    department: "Engineering",
    type: "CHECK_OUT" as AttendanceEventType,
    timestamp: "2026-07-01T17:05:00Z",
    status: "PRESENT" as AttendanceStatus,
    message: "Checked out. Total: 9h 3m.",
  },
  {
    id: "evt-009",
    employeeId: "emp-008",
    employeeName: "Tariq Al-Ghamdi",
    department: "Engineering",
    type: "CHECK_OUT" as AttendanceEventType,
    timestamp: "2026-07-01T17:02:00Z",
    status: "PRESENT" as AttendanceStatus,
    message: "Checked out. Total: 9h 4m.",
  },
  {
    id: "evt-010",
    employeeId: "emp-006",
    employeeName: "Ahmed Al-Dossari",
    department: "Engineering",
    type: "ADMIN_CORRECTION" as AttendanceEventType,
    timestamp: "2026-07-01T18:00:00Z",
    status: "HALF_DAY" as AttendanceStatus,
    message: "Record corrected by admin: marked as half day.",
  },
  {
    id: "evt-011",
    employeeId: "emp-005",
    employeeName: "Noura Al-Qahtani",
    department: "Sales",
    type: "REJECTED_LOCATION" as AttendanceEventType,
    timestamp: "2026-07-01T07:52:00Z",
    status: "ABSENT" as AttendanceStatus,
    message: "Check-in rejected: employee was 480 meters outside the allowed office radius.",
  },
];

// ---------------------------------------------------------------------------
// 8. Late Arrivals (today: 2026-07-02)
// ---------------------------------------------------------------------------

export const lateArrivals = [
  {
    id: "late-001",
    employeeId: "emp-008",
    employeeName: "Tariq Al-Ghamdi",
    department: "Engineering",
    date: "2026-07-02",
    checkInAt: "2026-07-02T08:30:00Z",
    lateMinutes: 30,
  },
  {
    id: "late-002",
    employeeId: "emp-003",
    employeeName: "Fatima Al-Zahrani",
    department: "Finance",
    date: "2026-07-02",
    checkInAt: "2026-07-02T09:15:00Z",
    lateMinutes: 75,
  },
  {
    id: "late-003",
    employeeId: "emp-003",
    employeeName: "Fatima Al-Zahrani",
    department: "Finance",
    date: "2026-07-01",
    checkInAt: "2026-07-01T08:47:00Z",
    lateMinutes: 47,
  },
];

// ---------------------------------------------------------------------------
// 9. Missing Checkout Records
// ---------------------------------------------------------------------------

export const missingCheckoutRecords = [
  {
    id: "mc-001",
    employeeId: "emp-004",
    employeeName: "Omar Al-Harbi",
    department: "Operations",
    date: "2026-07-01",
    checkInAt: "2026-07-01T08:00:00Z",
    status: "MISSING_CHECKOUT" as AttendanceStatus,
  },
  {
    id: "mc-002",
    employeeId: "emp-012",
    employeeName: "Faris Al-Rashidi",
    department: "Operations",
    date: "2026-07-02",
    checkInAt: null as string | null,
    status: "MISSING_CHECKOUT" as AttendanceStatus,
  },
];

// ---------------------------------------------------------------------------
// 10. Monthly Calendar Data (emp-002 — Khalid Bin Nasser, June 2026)
// Full prior month so the calendar grid shows all status types.
// ---------------------------------------------------------------------------

export const employeeMonthlyCalendar = [
  // Week 1
  {
    employeeId: "emp-002",
    date: "2026-06-01",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-01T07:59:00Z",
    checkOutAt: "2026-06-01T17:03:00Z",
    totalMinutes: 544,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-02",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-02T08:01:00Z",
    checkOutAt: "2026-06-02T17:00:00Z",
    totalMinutes: 539,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-03",
    status: "LATE" as AttendanceStatus,
    checkInAt: "2026-06-03T08:22:00Z",
    checkOutAt: "2026-06-03T17:05:00Z",
    totalMinutes: 523,
    isLate: true,
    lateMinutes: 22,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-04",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-04T07:57:00Z",
    checkOutAt: "2026-06-04T17:10:00Z",
    totalMinutes: 553,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-05",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-05T08:00:00Z",
    checkOutAt: "2026-06-05T17:00:00Z",
    totalMinutes: 540,
    isLate: false,
    lateMinutes: 0,
  },
  // Week 2
  {
    employeeId: "emp-002",
    date: "2026-06-08",
    status: "ABSENT" as AttendanceStatus,
    checkInAt: null as string | null,
    checkOutAt: null as string | null,
    totalMinutes: 0,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-09",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-09T08:03:00Z",
    checkOutAt: "2026-06-09T17:02:00Z",
    totalMinutes: 539,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-10",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-10T08:00:00Z",
    checkOutAt: "2026-06-10T17:00:00Z",
    totalMinutes: 540,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-11",
    status: "HALF_DAY" as AttendanceStatus,
    checkInAt: "2026-06-11T08:00:00Z",
    checkOutAt: "2026-06-11T12:15:00Z",
    totalMinutes: 255,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-12",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-12T07:55:00Z",
    checkOutAt: "2026-06-12T17:05:00Z",
    totalMinutes: 550,
    isLate: false,
    lateMinutes: 0,
  },
  // Week 3
  {
    employeeId: "emp-002",
    date: "2026-06-15",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-15T08:01:00Z",
    checkOutAt: "2026-06-15T17:00:00Z",
    totalMinutes: 539,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-16",
    status: "LATE" as AttendanceStatus,
    checkInAt: "2026-06-16T09:05:00Z",
    checkOutAt: "2026-06-16T17:00:00Z",
    totalMinutes: 475,
    isLate: true,
    lateMinutes: 65,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-17",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-17T08:00:00Z",
    checkOutAt: "2026-06-17T17:00:00Z",
    totalMinutes: 540,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-18",
    status: "MISSING_CHECKOUT" as AttendanceStatus,
    checkInAt: "2026-06-18T08:00:00Z",
    checkOutAt: null as string | null,
    totalMinutes: null as number | null,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-19",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-19T07:58:00Z",
    checkOutAt: "2026-06-19T17:03:00Z",
    totalMinutes: 545,
    isLate: false,
    lateMinutes: 0,
  },
  // Week 4
  {
    employeeId: "emp-002",
    date: "2026-06-22",
    status: "ON_LEAVE" as AttendanceStatus,
    checkInAt: null as string | null,
    checkOutAt: null as string | null,
    totalMinutes: 0,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-23",
    status: "ON_LEAVE" as AttendanceStatus,
    checkInAt: null as string | null,
    checkOutAt: null as string | null,
    totalMinutes: 0,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-24",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-24T08:02:00Z",
    checkOutAt: "2026-06-24T17:00:00Z",
    totalMinutes: 538,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-25",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-25T08:00:00Z",
    checkOutAt: "2026-06-25T17:05:00Z",
    totalMinutes: 545,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-26",
    status: "LATE" as AttendanceStatus,
    checkInAt: "2026-06-26T08:35:00Z",
    checkOutAt: "2026-06-26T17:00:00Z",
    totalMinutes: 505,
    isLate: true,
    lateMinutes: 35,
  },
  // Week 5
  {
    employeeId: "emp-002",
    date: "2026-06-29",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-29T07:59:00Z",
    checkOutAt: "2026-06-29T17:01:00Z",
    totalMinutes: 542,
    isLate: false,
    lateMinutes: 0,
  },
  {
    employeeId: "emp-002",
    date: "2026-06-30",
    status: "PRESENT" as AttendanceStatus,
    checkInAt: "2026-06-30T08:00:00Z",
    checkOutAt: "2026-06-30T17:00:00Z",
    totalMinutes: 540,
    isLate: false,
    lateMinutes: 0,
  },
];

// ---------------------------------------------------------------------------
// 11. Attendance Policy
// ---------------------------------------------------------------------------

export const attendancePolicy = {
  id: "policy-001",
  officeName: "Main Office — Riyadh",
  officeLatitude: 24.7136,
  officeLongitude: 46.6753,
  allowedRadiusMeters: 200,
  workStartTime: "08:00",
  timezone: "Asia/Riyadh",
  minimumFullDayMinutes: 420,
  minimumHalfDayMinutes: 210,
  active: true,
};
